
AnalyzeList = [1:10];

% File = zAddNTData({'2avy','1j5e'});
if isempty(File(1).Distance),
  for f = 1:length(File),
    c = cat(1,File(f).NT(1:File(f).NumNT).Center); % nucleotide centers
    File(f).Distance = zMutualDistance(c,16); % compute distances < 16 Angstroms
  end
end

Verbose = 1;
a = 0;

% -------------------------------------- Load JesseRyan composite alignment

load JesseRyan16SComposite

a = a+1;
Al(a).ModelStructure = JRComposite2AVY;
Al(a).InferStructure = JRComposite1J5E;
Al(a).Name           = 'Jesse-Ryan composite';

% -------------------------------------- Load Ryan's 3D to 3D alignment

load 16SalignmentInd

a = a+1;
Al(a).ModelStructure = ind2';
Al(a).InferStructure = ind1';
Al(a).Name           = 'Ryan 3D to 3D';

% -------------------------------------- Load Jesse's 3D to 3D alignment

[File1,i1,File2,i2] = zReadJesseAlignments('16S');

a = a+1;
Al(a).ModelStructure = i1';
Al(a).InferStructure = i2';
Al(a).Name           = 'Jesse 3D to 3D';

% ------------------------------ JAR3D alignment of 1j5e seq to 2avy structure

%>E. coli sequence from 2avy -1448.0515273252945 
ES = 'UGAA---GAGU<UUGAUCAUG>GCUC--AGAUUGAACGCUG--GCGGCAGG-{CCUAACA{CAUGCAA--GUC{GAACG{GUAA{CAGGAAGAAGC----------<UU>----------G-CUUCUUUGCUG}ACG}AGU}GGCGGACG-GGUGAGU-AAU-GUCUGGGAA-ACUGCCUGAUGGA--GGGGGAUAACUACUGG<AA>ACGGUAGCUAAUACCGC--AUAACGUC----------G<CA>A----------GACCAA-A-GAGGGGGACC----------U<UC>G----------GGCCUCUU-GCCAUCGGAUGUGCCCAGAU--GGG{AUUAGCUAGUAGGUGGG<GUAACGG>CUCACCUAGGCGACGAU}CCC-UA-GCUGGUCUG<AG>AGGAUGACCAGC-CACA----CUGGAACU<GAG>ACACGGUCCAG--ACUCC----------U<AC>G----------GGAGG--CAGCAG}UGGGGAAU}--AUUGC{ACAAUGGGC----------G<CA>A----------GCCUGAU}GCAG-CCAUGCCGCG-U-GUAUG{AAGAAGGCC----------U<UC>G----------GGUUGUAA}AGUAC--{UUUCAGCGGGGAGGAAGGGAGUAAAG<UUAAUAC>CUUUGCUC-AUUGACGUUACCCGCAGAAG}-AA---GC{ACCGGCUAACUCCG{UGCCAGC<AGCC>GCGGUAAUA}CGGAG-GGU}GC-AAGCGUUAAUCGG-AAUU--ACUG{GGCGUAAAGC--GCACGCAGGCG-GUUUGUU{AAG{UCAGAUGUGAAAUCCCCGGGC<UCA>ACCUGGGAACUGCAUCUGAUA}CU}GGCAAGC--{UUGAGUCUCGUAGAGGGGGGU-AGAAUUCCAGGUGUAGCG----------G<UGAA>A----------UGCGUAGAGAUCUGGAGGAAUACCG-GUGGC<GAAG>GCG-GCCCCCUGGACGAAGACUGAC}-GCUCAGGUGCG-AAAGCGUGGGGAGCAAACAGG----------<AUUAGAUAC>----------CCUGGUAGUCCACGCCGU--AAACGA{UGUCGACU-UGGAGGUUGUGCC------------<CUUGA>------------GGCGUGGCUUCCGG-AGC<UAAC>GCG-UUAAGUCGAC}-CGCC}U--GGGGA{GUACGGCC----------G<CA>A----------GGUUAA}AACUC-AAAUGAAU----{UG-ACGGGGGCCCGC{ACAA-GCGGUG-GAGCAUGUGGUUUAA-UUCG--------A<UGCA>A--------CGCGAAGAACCUUA-CCUGGUCUU-{GACAUCCACGGAA--GUUUUCA<GAGA>UGAGAAUGU-GCC----------<UUCG>----------GGA--ACCGUGAGAC}--{AGGUGCU{GCAUG{GCUGUCGUCA-GCUCGU-GUU<GUGA>AAUGU-UGGGU----------<UAAG>----------UCCCG-CAACGAGCGCAAC-CCUUA-UCCUUU{GUUGC{CAG{CGG----------<UCCG>----------GCCG}-G}G-AACUC}AAAGGA--{GACUGCCAGUG<AUA>A-ACUGGA-GGAAG}-GUGGGG--AUGACGUCAAGUCAU}CAU}GGC-CCUUAC}-GACCAGG-GCUACACACGUGCUA--C-{AAUGGCGCAUACAAAGAGAA{GCGACCUC<GCGA>GAGCAAGCG}GACCUCAUAAAGUGCGUC-GUAGU}C-CGGAUUGGAGUC----------U<GCA>A----------CUCGACUCCAUGAAG-UCG-GAAUCGCU-A{GUAAUCGUGGAU<CAGA>-AUGCCACGGUGA}A-UACGUUCC}CGGGCCUUGUACACAC}--CGCCCGUCACACCAUGGGAGUGGGUUGCAAAAGAAGUAGG{UAGCUUAA-CC----------U<UC>G----------GGAGGGCG}CUUACCACUUUGUGAUUCAUGACUGGGGUGAAGUCGUAACAAG-GU-AACCGUAGG<GGAA>CCUGCGGUU--G-----GAUCA';

%>T.th. sequence from 1j5e -1706.4187253750251 
TS = 'UGGA---GAGU<UUGAUCCUG>GCUC--AGGGUGAACGCUG--GCGGCGUG-{CCUAAGA{CAUGCAA--GUC{GUGCG{G---{GCCGCGGGGU-----------<UU>-----------UACUCCGUGGUC}-AG}CGG}CGG--ACG-GGUGAGU-AAC-GCGUGGGUGACCUACCCGGAAGA--GGGGGACAACCCGGGG<AA>ACUCGGGCUAAUCCCCC--AUGU-GGACCCGCCCC---<UU>---GGGGUGUGUCC-AA---AGGG----------------C<UU>U--------------GCCC-GCUUCCGGAUGGGCCCGCGU--CCC{AUCAGCUAGUUGGUGGG<GUAAUGG>CCCACCAAGGCGACGAC}GGG-UA-GCCGGUCUG<AG>AGGAUGGCCGGC-CACA----GGGGCACU<GAG>ACACGGGCCCC--ACUCC----------U<AC>G----------GGAGG--CAGCAG}UUAGGAAU}--CUUCC{GCAAUGGGC----------G<CA>A----------GCCUGAC}GGAG-CGACGCCGCU-U-GGAGG{AAGAAG-CCC---------U<UC>G---------GGG-UGUAA}ACUCC--{UG-AACCCGGGA-C-G-A-AACCC-C<CGACGAG>GGG-ACU-GACG--G--UACCGGGGUAAU}--A---GC{GCCGGCCAACUCCG{UGCCAGC<AGCC>GCGGUAAUA}CGGAG-GGC}GC-GAGCGUUACCCGG-AUUC--ACUG{GGCGUAAAGG--GCGUGUAGGCG-GCCUGGG{GCG{UCCCAUGUGAAAGACCACGGC<UCA>ACCGUGGGGGAGCGUGGGAUA}CG}CUCAGGC--{UAGACGGUGGGAGAGGGUGGU-GGAAUUCCCGGAGUAGCG----------G<UGAA>A----------UGCGCAGAUACCGGGAGGAACGCCG-AUGGC<GAAG>GCA-GCCACCUGGUCCACCCGUGAC}-GCUGAGGCGCG-AAAGCGUGGGGAGCAAACCGG----------<AUUAGAUAC>----------CCGGGUAGUCCACGCCCU--AAACGA{UGCGCGCU-AGGU-CUC-UGG-------------<GUCUC>-------------CUG-GGG-GCCGA-AGC<UAAC>GCG-UUAAGCGCGC}-CGCC}U--GGGGA{GUACGGCC----------G<CA>A----------GGCUGA}AACUC-AAAGGAAU----{UG-ACGGGGGCCCGC{ACAA-GCGGUG-GAGCAUGUGGUUUAA-UUCG--------A<AGCA>A--------CGCGAAGAACCUUA-CCAGGCCUU-{GACAUGCUAGGGAA-CCCGGGU<GAAA>GCCUGGGGU-GCCCC--------<GCGA>--------GGGGA-GCCCUAG-CAC}--{AGGUGCU{GCAUG{GCCGUCGUCA-GCUCGU-GCC<GUGA>GGUGU-UGGGU----------<UAAG>----------UCCCG-CAACGAGCGCAAC-CCCCG-CCGUUA{GUUGC{CAG{CGG----------<UUCG>----------GCCG}-G}GCA-CUC}UAACGG--{GACUGCCCGC-<GAA>-AGCGGGA-GGAAG}--GAGGG-GACGACGUCUGGUCAG}CAU}GGC-CCUUAC}-GGCCUGG-GCGACACACGUGCUA--C-{AAUGCCCACUACAAAGCGAU{GCCACCCG<GCAA>CGGGGAGCU}AAUCGCAAAAAGGUGGGCCCAGUU}--CGGAUUGGGGUC----------U<GCA>A----------CCCGACCCCAUGAAG-CCG-GAAUCGCU-A{GUAAUCGCGGAU<CAGC>CAUGCCGCGGUGA}A-UACGUUCC}CGGGCCUUGUACACAC}--CGCCCGUCACGCCAUGGGAGCGGGCUCUACCCGA----AG{UCGCCGGGAGCC---------U<AC>G---------GGC-AGGCG}CC---GAGGGUAGGGCCCGUGACUGGGGCGAAGUCGUAACAAG-GU-AGCUGUACC<GGAA>GGUGCGGCU-GGAUCACUUUCU';

[i1,i2] = pGetAlignedIndices(ES,TS);

a = a+1;
Al(a).ModelStructure = i1;
Al(a).InferStructure = i2;
Al(a).Name           = 'JAR3D Extensible BISTI Subst LR';

% ------------------------------ JAR3D alignment of 1j5e seq to 2avy structure

%>E. coli sequence from 2avy -1454.2420647192616 

ES = 'UGAA---GAGU<UUGAUCAUG>GCUC--AGAUUGAACGCUG--GCGGCAGG-{CCUAACA{CAUGCAA--GUC{GAACG{GUAA{CAGGAAGAAGC----------<UU>----------G-CUUCUUUGCUG}ACG}AGU}GGCGGACG-GGUGAGU-AAU-GUCUGGGAA-ACUGCCUGAUGGA--GGGGGAUAACUACUGG<AA>ACGGUAGCUAAUACCGC--AUAACGUC----------G<CA>A----------GACCAA-A-GAGGGGGACC----------U<UC>G----------GGCCUCUU-GCCAUCGGAUGUGCCCAGAU--GGG{AUUAGCUAGUAGGUGGG<GUAACGG>CUCACCUAGGCGACGAU}CCC-UA-GCUGGUCUG<AG>AGGAUGACCAGC-CACA----CUGGAACU<GAG>ACACGGUCCAG--ACUCC----------U<AC>G----------GGAGG--CAGCAG}UGGGGAAU}--AUUGC{ACAAUGGGC----------G<CA>A----------GCCUGAU}GCAG-CCAUGCCGCG-U-GUAUG{AAGAAGGCC----------U<UC>G----------GGUUGUAA}AGUAC--{UUUCAGCGGGGAGGAAGGGAGUAAAG<UUAAUAC>CUUUGCUC-AUUGACGUUACCCGCAGAAG}-AA---GC{ACCGGCUAACUCCG{UGCCAGC<AGCC>GCGGUAAUA}CGGAG-GGU}GC-AAGCGUUAAUCGG-AAUU--ACUG{GGCGUAAAGC--GCACGCAGGCG-GUUUGUU{AAG{UCAGAUGUGAAAUCCCCGGGC<UCA>ACCUGGGAACUGCAUCUGAUA}CU}GGCAAGC--{UUGAGUCUCGUAGAGGGGGGU-AGAAUUCCAGGUGUAGCG----------G<UGAA>A----------UGCGUAGAGAUCUGGAGGAAUACCG-GUGGC<GAAG>GCG-GCCCCCUGGACGAAGACUGAC}-GCUCAGGUGCG-AAAGCGUGGGGAGCAAACAGG----------<AUUAGAUAC>----------CCUGGUAGUCCACGCCGU--AAACGA{UGUCGACU-UGGAGGUUGUGCC------------<CUUGA>------------GGCGUGGCUUCCGG-AGC<UAAC>GCG-UUAAGUCGAC}-CGCC}U--GGGGA{GUACGGCC----------G<CA>A----------GGUUAA}AACUC-AAAUGAAU----{UG-ACGGGGGCCCGC{ACAA-GCGGUG-GAGCAUGUGGUUUAA-UUCG--------A<UGCA>A--------CGCGAAGAACCUUA-CCUGGUCUU-{GACAUCCACGGAA--GUUUUCA<GAGA>UGAGAAUGU-GCC----------<UUCG>----------GGA--ACCGUGAGAC}--{AGGUGCU{GCAUG{GCUGUCGUCA-GCUCGU-GUU<GUGA>AAUGU-UGGGU----------<UAAG>----------UCCCG-CAACGAGCGCAAC-CCUUA-UCCUUU{GUUGC{CAG{CGG----------<UCCG>----------GCCG}-G}G-AACUC}AAAGGA--{GACUGCCAGUG<AUA>A-ACUGGA-GGAAG}-GUGGGG--AUGACGUCAAGUCAU}CAU}GGC-CCUUAC}-GACCAGG-GCUACACACGUGCUA--C-{AAUGGCGCAUACAAAGAGAA{GCGACCUC<GCGA>GAGCAAGCG}GACCUCAUAAAGUGCGUC-GUAGU}C-CGGAUUGGAGUC----------U<GCA>A----------CUCGACUCCAUGAAG-UCG-GAAUCGCU-A{GUAAUCGUGGAU<CAGA>-AUGCCACGGUGA}A-UACGUUCC}CGGGCCUUGUACACAC}--CGCCCGUCACACCAUGGGAGUGGGUUGCAAAAGAAGUAGG{UAGCUUAA-CC----------U<UC>G----------GGAGGGCG}CUUACCACUUUGUGAUUCAUGACUGGGGUGAAGUCGUAACAAG-GU-AACCGUAGG<GGAA>CCUGCGGUU--------GGAUCA';

%>T.th. sequence from 1j5e -1712.0964047104503 
TS = 'UGGA---GAGU<UUGAUCCUG>GCUC--AGGGUGAACGCUG--GCGGCGUG-{CCUAAGA{CAUGCAA--GUC{GUGCG{G---{GCCGCGGGGU-----------<UU>-----------UACUCCGUGGUC}-AG}CGG}CGG--ACG-GGUGAGU-AAC-GCGUGGGUGACCUACCCGGAAGA--GGGGGACAACCCGGGG<AA>ACUCGGGCUAAUCCCCC--AUGU-GGACCCGCCCC---<UU>---GGGGUGUGUCC-AA---AGGG----------------C<UU>U--------------GCCC-GCUUCCGGAUGGGCCCGCGU--CCC{AUCAGCUAGUUGGUGGG<GUAAUGG>CCCACCAAGGCGACGAC}GGG-UA-GCCGGUCUG<AG>AGGAUGGCCGGC-CACA----GGGGCACU<GAG>ACACGGGCCCC--ACUCC----------U<AC>G----------GGAGG--CAGCAG}UUAGGAAU}--CUUCC{GCAAUGGGC----------G<CA>A----------GCCUGAC}GGAG-CGACGCCGCU-U-GGAGG{AAGAAG-CCC---------U<UC>G---------GGG-UGUAA}ACUCC--{UG-AACCCGGGA-C-G-A-AACCC-C<CGACGAG>GGG-ACU-GACG--G--UACCGGGGUAAU}--A---GC{GCCGGCCAACUCCG{UGCCAGC<AGCC>GCGGUAAUA}CGGAG-GGC}GC-GAGCGUUACCCGG-AUUC--ACUG{GGCGUAAAGG--GCGUGUAGGCG-GCCUGGG{GCG{UCCCAUGUGAAAGACCACGGC<UCA>ACCGUGGGGGAGCGUGGGAUA}CG}CUCAGGC--{UAGACGGUGGGAGAGGGUGGU-GGAAUUCCCGGAGUAGCG----------G<UGAA>A----------UGCGCAGAUACCGGGAGGAACGCCG-AUGGC<GAAG>GCA-GCCACCUGGUCCACCCGUGAC}-GCUGAGGCGCG-AAAGCGUGGGGAGCAAACCGG----------<AUUAGAUAC>----------CCGGGUAGUCCACGCCCU--AAACGA{UGCGCGCU-AGGU-CUC-UGG-------------<GUCUC>-------------CUG-GGG-GCCGA-AGC<UAAC>GCG-UUAAGCGCGC}-CGCC}U--GGGGA{GUACGGCC----------G<CA>A----------GGCUGA}AACUC-AAAGGAAU----{UG-ACGGGGGCCCGC{ACAA-GCGGUG-GAGCAUGUGGUUUAA-UUCG--------A<AGCA>A--------CGCGAAGAACCUUA-CCAGGCCUU-{GACAUGCUAGGGAA-CCCGGGU<GAAA>GCCUGGGGU-GCCCC--------<GCGA>--------GGGGA-GCCCUAG-CAC}--{AGGUGCU{GCAUG{GCCGUCGUCA-GCUCGU-GCC<GUGA>GGUGU-UGGGU----------<UAAG>----------UCCCG-CAACGAGCGCAAC-CCCCG-CCGUUA{GUUGC{CAG{CGG----------<UUCG>----------GCCG}-G}GCA-CUC}UAACGG--{GACUGCCCGC-<GAA>-AGCGGGA-GGAAG}--GAGGG-GACGACGUCUGGUCAG}CAU}GGC-CCUUAC}-GGCCUGG-GCGACACACGUGCUA--C-{AAUGCCCACUACAAAGCGAU{GCCACCCG<GCAA>CGGGGAGCU}AAUCGCAAAAAGGUGGGCCCAGUU}--CGGAUUGGGGUC----------U<GCA>A----------CCCGACCCCAUGAAG-CCG-GAAUCGCU-A{GUAAUCGCGGAU<CAGC>CAUGCCGCGGUGA}A-UACGUUCC}CGGGCCUUGUACACAC}--CGCCCGUCACGCCAUGGGAGCGGGCUCUACCCGA----AG{UCGCCGGGAGCC---------U<AC>G---------GGC-AGGCG}CC---GAGGGUAGGGCCCGUGACUGGGGCGAAGUCGUAACAAG-GU-AGCUGUACC<GGAA>GGUGCGGCU--GGAUCACUUUCU';

[i1,i2] = pGetAlignedIndices(ES,TS);

a = a+1;
Al(a).ModelStructure = i1;
Al(a).InferStructure = i2;
Al(a).Name           = 'JAR3D Extensible BISTI subst';


% ------------------------------ JAR3D alignment of 1j5e seq to 2avy structure

% >E. coli sequence from 2avy -1888.019637265034 

ES = 'UGAA---GAGU<UUGAUCAUG>GCUC--AGAUUGAACGC--{UGGCGGCAGG-{CCUA{A-{CACA----U-{G-CAA{G-UCGAACGGUAACAGGAAGAAG-<CU>--UGCUUCUUUGCUGACGAG-UGG-CG}GAC}-G---GGUGAGU-AAU-GUCUGGGAA-ACUGCCUGAUGGA--GGGGGAUAACUACUGG<AA>ACGGUAGCUAAUACCGC--A-UAACGUCG-<CA>-AGACCAAA-G---AGGGGGACCU-----<UC>-----GGGCCUCUU-GCCAUCGGAUGUGCCCAGAU--GGG{AUUAGCUAGUAGGUGGG<GUAACGG>CUCACCUAGGCGACGAU}CCC-UA-GCUGGUCUG<AG>AGGAUGACCAGC-CACA----CUGGAACU<GAG>ACACGGUCCAG--ACUCCU-<AC>-GGGAGG---CAG}-C}AGU-G}--GGGA{AU-AUUGCACAAUG-<GG>-CGCAAGCCUGA-U}GCAG-CCAUGCCGC}G-U-GUAUG{AAGA-AG--G----CCU----<UC>----GGG----U--UG-UAA}AGUAC--{UUUCAGCGGGGAGGAAG{GGAGUAAAG<UUAAUAC>CUUUGCUCAU}UGACGUUACCCGCAGAAG}-AA---GC{ACCGGCUAACUCCG{UGCCAGC<AGCC>GCGGUAAUA}CGGAG-GGU}GC-AAGCGUUAAUCGG-AAUU--ACUG{GGCGUAAAGC--GCACGCAGGCG-GUUUGUU{AAG{UCAGAUGUGAAAUCCCCGGGC<UCA>ACCUGGGAACUGCAUCUGAUA}CU}GGCAAGC--{UUGAGUCUCGUAGA{GGGGGGU-AGAAUUCCAGGUGUAGCGG<UGAA>AUGCGUAGAGAUCUGGAGGAAUACCG-GUGGC<GAAG>GCG-GCCCCCU}GGACGAAGACUGAC}-GCUCAGGUGCG-AAAGCGUGGGGAGCAAACAGG<AUUAGAUAC>CCUGGUAGUCCACGCC--G{UAAACGAU--GUCGACU-UG--GAGGUUGUGCC-<CUUGA>-GGCGUGGCUUC--CG-GAGCUAA---C--<GCGU>--U-AAGUCGAC}-CGCC}U--GGGGA{GUACGGCCGCAA-<GG>-UUAAAACUCA}AAUGAAU----{UG-ACGGGGGCCCGC{ACAA-GCGGUG-GAGCAUGUGGUU{UAA-UUCGA<UGCA>ACGCGAAGAACCUUAC-CUGGUCU-{UGACAUCCACGGAA--GUUUUCA<GAGA>UGAGAAU-G-UGCC-<UUCG>-GGAA---CCGUGAGAC}--{AGGUGCU{GCAUG{GCUGUCGUCA-GCUCGU-GUU<GUGA>AAUGU-UGGGU-<UAAG>-UCCCG-CAACGAGCGCAAC-CCUUA-UCCUUUGUUG{CCAGCG<GUCC>GGCCGGG}AACUCAAAGGA--{GACUGCCAGUG<AUA>A-ACUGGAGGAAGG}-UGGGG--AUGACGUCAAGUCAU}CAU}GGC-CCUUAC}-GACCAG--G}GCUACACACGUGCUA--C-AAUGGCGCAUACAAAGAGAA{GCGACCUC<GCGA>GAGCAAGCG}GACCUCAUAAAGUGCGUCGUAGUC-CGGAUUGGAGUCU<GCA>ACUCGACUCCAUGAAG-UCG-GAAUCGCU-A{GUAAUCGUGGAU<CAGA>A-UGCCACGGUGA}A-UACGUUCC}CGGGCCUUGUACACA}--CCGCCCGUCACACCAUGGGAGUGGGUUGCAAAAGAAGUAGG{UAGCUUAACCU--<UC>--GGGAGGGCG}CUUACCACUUUGUGAUUCAUGACUGGGGUGAAGUCGUAACAAG-GU-AACCGUAGG<GGAA>CCUGCGGUU--G-----GAUCA';


% >T.th. sequence from 1j5e -1987.4380019080618 

TS = 'UGGA---GAGU<UUGAUCCUG>GCUC--AGGGUGAACGC--{U-GGCGGC---{G-UG{CC{UAAGA--CAU{GCAAG{U-CGU-GCGGG---CCGCGGGGU-<UU>-UACUCCGUGG---UCAGC-GGCG-GA}CGG}GUG--AGUA----AC--GCGUGGGUGACCUACCCGGAAGA--GGGGGACAACCCGGGG<AA>ACUCGGGCUAAUCCCCC--A--UGUGGAC-<CC>-GCCCCUU--G---GGGUG--UGU-CCA-<AA>-GGG-CUU-UGCCC-GCUUCCGGAUGGGCCCGCGU--CCC{AUCAGCUAGUUGGUGGG<GUAAUGG>CCCACCAAGGCGACGAC}GGG-UA-GCCGGUCUG<AG>AGGAUGGCCGGC-CACA----GGGGCACU<GAG>ACACGGGCCCC--ACUCCU-<AC>-GGGAGG--CAGC}AG}UUAGG}--A-AU{CU-UCCGCAAUGGGC<GC>AAGCCUGACGGA-G}CG-A---CGCCGCU}--U-GGAGG{AAGA-AG------CCCU----<UC>----GGGG------UG-UAA}ACUCC--{UG-AACCCGGGAC----{GAAACCC-C<CGACGAG>GGG-ACUGAC}----GGUACCGGGGUAAU}--A---GC{GCCGGCCAACUCCG{UGCCAGC<AGCC>GCGGUAAUA}CGGAG-GGC}GC-GAGCGUUACCCGG-AUUC--ACUG{GGCGUAAAGG--GCGUGUAGGCG-GCCUGGG{GCG{UCCCAUGUGAAAGACCACGGC<UCA>ACCGUGGGGGAGCGUGGGAUA}CG}CUCAGGC--{UAGACGGUGGGAGA{GGGUGGU-GGAAUUCCCGGAGUAGCGG<UGAA>AUGCGCAGAUACCGGGAGGAACGCCG-AUGGC<GAAG>GCA-GCCACCU}GGUCCACCCGUGAC}-GCUGAGGCGCG-AAAGCGUGGGGAGCAAACCGG<AUUAGAUAC>CCGGGUAGUCCACGCC--C{UAAACGAU---GCG--CGCUAG-GUCUCUG--G-<GUCUC>-C--UGGGGGC-CGAAGC--UAA----C--<GCGU>--U-AAGCGCGC}-CGCC}U--GGGGA{GUACGGCCGCAA-<GG>-CUGAAACUCA}AAGGAAU----{UG-ACGGGGGCCCGC{ACAA-GCGGUG-GAGCAUGUGGUU{UAA-UUCGA<AGCA>ACGCGAAGAACCUUAC-CAGGCCU-{UGACAUGCUAGGGAA-CCCGGGU<GAAA>GCCUGGGGU-GCCCC<GCGA>GGGGA-GCCCUAG-CAC}--{AGGUGCU{GCAUG{GCCGUCGUCA-GCUCGU-GCC<GUGA>GGUGU-UGGGU-<UAAG>-UCCCG-CAACGAGCGCAAC-CCCCG-CCGUUAGUUG{CCAGCG<GUUC>GGCCGGG}CACUCUAACGG--{GACUGCCCGC-<GAA>-AGCGGGAGGAAGG}--AGGG-GACGACGUCUGGUCAG}CAU}GGC-CCUUAC}-GGCCUG--G}GCGACACACGUGCUA--C-AAUGCCCACUACAAAGCGAU{GCCACCCG<GCAA>CGGGGAGCU}AAUCGCAAAAAGGUGGGCCCAGUU-CGGAUUGGGGUCU<GCA>ACCCGACCCCAUGAAG-CCG-GAAUCGCU-A{GUAAUCGCGGAU<CAGC>CAUGCCGCGGUGA}A-UACGUUCC}CGGGCCUUGUACACA}--CCGCCCGUCACGCCAUGGGAGCGGGCUCUACCCGAAGUCGC{CGGGA---GCC--<UA>--CGG--GCAG}GCGCCGAGGGUAGGGCCCGUGACUGGGGCGAAGUCGUAACAAG-GU-AGCUGUACC<GGAA>GGUGCGGCU-GGAUCACUUUCU';

[i1,i2] = pGetAlignedIndices(ES,TS);

a = a+1;
Al(a).ModelStructure = i1;
Al(a).InferStructure = i2;
Al(a).Name           = 'JAR3D 2002 IM Extensible';

% ------------------------------ JAR3D alignment of 1j5e seq to 2avy structure

% >E. coli sequence from 2avy -1661.9402926282287 

ES = 'UGAA---GAGU<UUGAUCAUG>GCUC--AGAUUGAACGC--{UGGCGGCAGG-{CCUAA{CA{CAUGCAA--GUC{GAACG{GUAACAGGAAGAAGC<UU>-GCUUCUUUGCUGACG}AGU}GGCGGACG-GGUGAGU-AAU-GUCUGGGAA-ACUGCCUGAUGGA--GGGGGAUAACUACUGG<AA>ACGGUAGCUAAUACCGC--AUAACGUCG<CA>AGACCAA-A-GAGGGGGA--CCU<UC>GGGCCUCUU-GCCAUCGGAUGUGCCCAGAU--GGG{AUUAGCUAGUAGGUGGG<GUAACGG>CUCACCUAGGCGACGAU}CCC-UA-GCUGGUCUG<AG>AGGAUGACCAGC-CACA----CUGGAACU<GAG>ACACGGUCCAG--ACUCCU<AC>GGGAGG--CAGCAG}UG}GGG---A}--AUAU{UGCACAAUGG<GC>GCAAGCCUGA}UGCAG-CCAUGCCGC}G-U-GUAUG{AAGAAGGCCU<UC>GGGUUGUAA}AGUAC--{UUUCAGCGGGGAGGAAG{GGAGUAAAG<UUAAUAC>CUUUGCUCAU}UGACGUUACCCGCAGAAG}-AA---GC{ACCGGCUAACUCCG{UGCCAGC<AGCC>GCGGUAAUA}CGGAG-GGU}GC-AAGCGUUAAUCGG-AAUU--ACUG{GGCGUAAAGC--GCACGCAGGCG-GUUUGUU{AAG{UCAGAUGUGAAAUCCCCGGGC<UCA>ACCUGGGAACUGCAUCUGAUA}CU}GGCAAGC--{UUGAGUCUCGUAGA{GGGGGGU-AGAAUUCCAGGUGUAGCGG<UGAA>AUGCGUAGAGAUCUGGAGGAAUACCG-GUGGC<GAAG>GCG-GCCCCCU}GGACGAAGACUGAC}-GCUCAGGUGCG-AAAGCGUGGGGAGCAAACAGG<AUUAGAUAC>CCUGGUAGUCCACGCCGU--AAACGA{UGUCGACU-UGGAGGUUGUGCC<CUUGA>GGCGUGGCUUCCGG-AGC<UAAC>GCG-UUAAGUCGAC}-CGCC}U--GGGGA{GUACGGCCG<CA>AGGUUAA}AACUCAAAUGAAU----{UG-ACGGGGGCCCGC{ACAA-GCGGUG-GAGCAUGUGGUU{UAAUU-CGA<UGCA>ACGCGAAGAACCUUAC-CUGGUCU-{UGACAUCCACGGAA--GUUUUCA<GAGA>UGAGAAU--GU-GCC<UUCG>GGA---ACCGUGAGAC}--{AGGUGCU{GCAUG{GCUGUCGUCA-GCUCGU-GUU<GUGA>AAUGU-UGGGU<UAAG>UCCCG-CAACGAGCGCAAC-CCUUA-UCCUUUGUUGCCAG{CGG<UCCG>GCCG}GGAACUCAAAGGA--{GACUGCCAGUG<AUA>A-ACUGGAGGAAGG}-UGGGG--AUGACGUCAAGUCAU}CAU}GGC-CCUUAC}-GACCAG--G}GCUACACACGUGCUA--C-AAUGGCGCAUACAAAGAGAA{GCGACCUC<GCGA>GAGCAAGCG}GACCUCAUAAAGUGCGUCGUAGU--CCGGAUUGGAGUC<UGC>AACUCGACUCCAUGAAG-UCG-GAAUCGCU-A{GUAAUCGUGGAU<CAGA>A-UGCCACGGUGA}A-UACGUUCC}CGGGCCUUGUACACA}--CCGCCCGUCACACCAUGGGAGUGGGUUGCAAAAGAAGUAGG{UAGCUUAACCU<UC>GGGAGGGCG}CUUACCACUUUGUGAUUCAUGACUGGGGUGAAGUCGUAACAAG-GU-AACCGUAGG<GGAA>CCUGCGGUU--G-----GAUCA';


% >T.th. sequence from 1j5e -1798.11196029636 

TS = 'UGGA---GAGU<UUGAUCCUG>GCUC--AGGGUGAACGC--{UGGCGGCGUG-{CCUAA{GA{CAUGC----AAG{U-CGU{GCG-GGCCGCGGGGU<UU>UACUCCGUGGUCAGCG}GCG}GAC----G-GGUGAGU-AAC-GCGUGGGUGACCUACCCGGAAGA--GGGGGACAACCCGGGG<AA>ACUCGGGCUAAUCCCCC--AUGUGGACC<CG>CCCCUUG---GGGUGUGUCCAAA<GG>GCUUUGCCC-GCUUCCGGAUGGGCCCGCGU--CCC{AUCAGCUAGUUGGUGGG<GUAAUGG>CCCACCAAGGCGACGAC}GGG-UA-GCCGGUCUG<AG>AGGAUGGCCGGC-CACA----GGGGCACU<GAG>ACACGGGCCCC--ACUCCU<AC>GGGAGG--CAGCAG}UU}AGGAAUC}--UUCC{GCAAUGGGCG<CA>AGC--CUGAC}-GGAG-CGACGCCGC}U-U-GGAGG{AAGAAGCCCU<UC>GGGGUGUAA}ACUCC--{UG-AACCCGGGAC----{GAAACCC-C<CGACGAG>GGG-ACUGAC}----GGUACCGGGGUAAU}--A---GC{GCCGGCCAACUCCG{UGCCAGC<AGCC>GCGGUAAUA}CGGAG-GGC}GC-GAGCGUUACCCGG-AUUC--ACUG{GGCGUAAAGG--GCGUGUAGGCG-GCCUGGG{GCG{UCCCAUGUGAAAGACCACGGC<UCA>ACCGUGGGGGAGCGUGGGAUA}CG}CUCAGGC--{UAGACGGUGGGAGA{GGGUGGU-GGAAUUCCCGGAGUAGCGG<UGAA>AUGCGCAGAUACCGGGAGGAACGCCG-AUGGC<GAAG>GCA-GCCACCU}GGUCCACCCGUGAC}-GCUGAGGCGCG-AAAGCGUGGGGAGCAAACCGG<AUUAGAUAC>CCGGGUAGUCCACGCCCU--AAAC--{GAUGCGC--GCUAGGUCUCUGG<GUCUC>CUGGGGGCCGAAGC-UAA<CGCG>UUA----AGCGCGC}-CGCC}U--GGGGA{GUACGGCCG<CA>AGGCUGA}AACUCAAAGGAAU----{UG-ACGGGGGCCCGC{ACAA-GCGGUG-GAGCAUGUGGUU{UAAUU-CGA<AGCA>ACGCGAAGAACCUUAC-CAGGCCU-{UGACAUGCUAGGGAA-CCCGGGU<GAAA>GCCUGGGGUGC-CCC<GCGA>GGG-GAGCCCUAGCAC}--{AGGUGCU{GCAUG{GCCGUCGUCA-GCUCGU-GCC<GUGA>GGUGU-UGGGU<UAAG>UCCCG-CAACGAGCGCAAC-CCCCG-CCGUUAGUUGCCAG{CGG<UUCG>GCCG}GGCACUCUAACGG--{GACUGCCCGC-<GAA>-AGCGGGAGGAAGG}--AGGG-GACGACGUCUGGUCAG}CAU}GGC-CCUUAC}-GGCCUG--G}GCGACACACGUGCUA--C-AAUGCCCACUACAAAGCGAU{GCCACCCG<GCAA>CGGGGAGCU}AAUCGCAAAAAGGUGGGCCCAGU--UCGGAUUGGGGUC<UGC>AACCCGACCCCAUGAAG-CCG-GAAUCGCU-A{GUAAUCGCGGAU<CAGC>CAUGCCGCGGUGA}A-UACGUUCC}CGGGCCUUGUACACA}--CCGCCCGUCACGCCAUGGGAGCGGGCUCUACCCGAAGUCGC{CGGGA---GCC<UA>CGG--GCAG}GCGCCGAGGGUAGGGCCCGUGACUGGGGCGAAGUCGUAACAAG-GU-AGCUGUACC<GGAA>GGUGCGGCU-GGAUCACUUUCU';

[i1,i2] = pGetAlignedIndices(ES,TS);

a = a+1;
Al(a).ModelStructure = i1;
Al(a).InferStructure = i2;
Al(a).Name           = 'JAR3D Motifs 2002 IM';

% ------------------------------ JAR3D alignment of 1j5e seq to 2avy structure

% >E. coli sequence from 2avy -1661.9402926282287 

ES = 'UGAA---GAGU<UUGAUCAUG>GCUC--AGAUUGAACGC--{UGGCGGCAGG-{CCUAA{CA{CAUGCAA--GUC{GAACG{GUAACAGGAAGAAGC<UU>-GCUUCUUUGCUGACG}AGU}GGCGGACG-GGUGAGU-AAU-GUCUGGGAA-ACUGCCUGAUGGA--GGGGGAUAACUACUGG<AA>ACGGUAGCUAAUACCGC--AUAACGUCG<CA>AGACCAA-A-GAGGGGGA--CCU<UC>GGGCCUCUU-GCCAUCGGAUGUGCCCAGAU--GGG{AUUAGCUAGUAGGUGGG<GUAACGG>CUCACCUAGGCGACGAU}CCC-UA-GCUGGUCUG<AG>AGGAUGACCAGC-CACA----CUGGAACU<GAG>ACACGGUCCAG--ACUCCU<AC>GGGAGG--CAGCAG}UG}GGG-AAU}--AUUGC{ACAAUGGGCG<CA>AGCCUGAU}GCAG-CCAUGCCGC}G-U-GUAUG{AAGAAGGCCU<UC>GGGUUGUAA}AGUAC--{UUUCAGCGGGGAGGAAG{GGAGUAAAG<UUAAUAC>CUUUGCUCAU}UGACGUUACCCGCAGAAG}-AA---GC{ACCGGCUAACUCCG{UGCCAGC<AGCC>GCGGUAAUA}CGGAG-GGU}GC-AAGCGUUAAUCGG-AAUU--ACUG{GGCGUAAAGC--GCACGCAGGCG-GUUUGUU{AAG{UCAGAUGUGAAAUCCCCGGGC<UCA>ACCUGGGAACUGCAUCUGAUA}CU}GGCAAGC--{UUGAGUCUCGUAGA{GGGGGGU-AGAAUUCCAGGUGUAGCGG<UGAA>AUGCGUAGAGAUCUGGAGGAAUACCG-GUGGC<GAAG>GCG-GCCCCCU}GGACGAAGACUGAC}-GCUCAGGUGCG-AAAGCGUGGGGAGCAAACAGG<AUUAGAUAC>CCUGGUAGUCCACGCCGU--AAACGA{UGUCGACU-UGGAGGUUGUGCC<CUUGA>GGCGUGGCUUCCGG-AGC<UAAC>GCG-UUAAGUCGAC}-CGCC}U--GGGGA{GUACGGCCG<CA>AGGUUAA}AACUCAAAUGAAU----{UG-ACGGGGGCCCGC{ACAA-GCGGUG-GAGCAUGUGGUU{UAAUU-CGA<UGCA>ACGCGAAGAACCUUAC-CUGGUCU-{UGACAUCCACGGAA--GUUUUCA<GAGA>UGAGAAU--GU-GCC<UUCG>GGA---ACCGUGAGAC}--{AGGUGCU{GCAUG{GCUGUCGUCA-GCUCGU-GUU<GUGA>AAUGU-UGGGU<UAAG>UCCCG-CAACGAGCGCAAC-CCUUA-UCCUUUGUUGCCAG{CGG<UCCG>GCCG}GGAACUCAAAGGA--{GACUGCCAGUG<AUA>A-ACUGGAGGAAGG}-UGGGG--AUGACGUCAAGUCAU}CAU}GGC-CCUUAC}-GACCAG--G}GCUACACACGUGCUA--C-AAUGGCGCAUACAAAGAGAA{GCGACCUC<GCGA>GAGCAAGCG}GACCUCAUAAAGUGCGUCGUAGUC-CGGAUUGGAGUCU<GCA>ACUCGACUCCAUGAAG-UCG-GAAUCGCU-A{GUAAUCGUGGAU<CAGA>A-UGCCACGGUGA}A-UACGUUCC}CGGGCCUUGUACACA}--CCGCCCGUCACACCAUGGGAGUGGGUUGCAAAAGAAGUAGG{UAGCUUAACCU<UC>GGGAGGGCG}CUUACCACUUUGUGAUUCAUGACUGGGGUGAAGUCGUAACAAG-GU-AACCGUAGG<GGAA>CCUGCGGUU--G-----GAUCA';

% >T.th. sequence from 1j5e -1798.11196029636 

TS = 'UGGA---GAGU<UUGAUCCUG>GCUC--AGGGUGAACGC--{UGGCGGCGUG-{CCUAA{GA{CAUGC----AAG{U-CGU{GCG-GGCCGCGGGGU<UU>UACUCCGUGGUCAGCG}GCG}GAC----G-GGUGAGU-AAC-GCGUGGGUGACCUACCCGGAAGA--GGGGGACAACCCGGGG<AA>ACUCGGGCUAAUCCCCC--AUGUGGACC<CG>CCCCUUG---GGGUGUGUCCAAA<GG>GCUUUGCCC-GCUUCCGGAUGGGCCCGCGU--CCC{AUCAGCUAGUUGGUGGG<GUAAUGG>CCCACCAAGGCGACGAC}GGG-UA-GCCGGUCUG<AG>AGGAUGGCCGGC-CACA----GGGGCACU<GAG>ACACGGGCCCC--ACUCCU<AC>GGGAGG--CAGCAG}UU}AGGAAUC}--UU-CC{GCAAUGGGCG<CA>AGCCUGAC}GGAG-CGACGCCGC}U-U-GGAGG{AAGAAGCCCU<UC>GGGGUGUAA}ACUCC--{UG-AACCCGGGAC----{GAAACCC-C<CGACGAG>GGG-ACUGAC}----GGUACCGGGGUAAU}--A---GC{GCCGGCCAACUCCG{UGCCAGC<AGCC>GCGGUAAUA}CGGAG-GGC}GC-GAGCGUUACCCGG-AUUC--ACUG{GGCGUAAAGG--GCGUGUAGGCG-GCCUGGG{GCG{UCCCAUGUGAAAGACCACGGC<UCA>ACCGUGGGGGAGCGUGGGAUA}CG}CUCAGGC--{UAGACGGUGGGAGA{GGGUGGU-GGAAUUCCCGGAGUAGCGG<UGAA>AUGCGCAGAUACCGGGAGGAACGCCG-AUGGC<GAAG>GCA-GCCACCU}GGUCCACCCGUGAC}-GCUGAGGCGCG-AAAGCGUGGGGAGCAAACCGG<AUUAGAUAC>CCGGGUAGUCCACGCCCU--AAAC--{GAUGCGC--GCUAGGUCUCUGG<GUCUC>CUGGGGGCCGAAGC-UAA<CGCG>UUA----AGCGCGC}-CGCC}U--GGGGA{GUACGGCCG<CA>AGGCUGA}AACUCAAAGGAAU----{UG-ACGGGGGCCCGC{ACAA-GCGGUG-GAGCAUGUGGUU{UAAUU-CGA<AGCA>ACGCGAAGAACCUUAC-CAGGCCU-{UGACAUGCUAGGGAA-CCCGGGU<GAAA>GCCUGGGGUGC-CCC<GCGA>GGG-GAGCCCUAGCAC}--{AGGUGCU{GCAUG{GCCGUCGUCA-GCUCGU-GCC<GUGA>GGUGU-UGGGU<UAAG>UCCCG-CAACGAGCGCAAC-CCCCG-CCGUUAGUUGCCAG{CGG<UUCG>GCCG}GGCACUCUAACGG--{GACUGCCCGC-<GAA>-AGCGGGAGGAAGG}--AGGG-GACGACGUCUGGUCAG}CAU}GGC-CCUUAC}-GGCCUG--G}GCGACACACGUGCUA--C-AAUGCCCACUACAAAGCGAU{GCCACCCG<GCAA>CGGGGAGCU}AAUCGCAAAAAGGUGGGCCCAGUU-CGGAUUGGGGUCU<GCA>ACCCGACCCCAUGAAG-CCG-GAAUCGCU-A{GUAAUCGCGGAU<CAGC>CAUGCCGCGGUGA}A-UACGUUCC}CGGGCCUUGUACACA}--CCGCCCGUCACGCCAUGGGAGCGGGCUCUACCCGAAGUCGC{CGGGA---GCC<UA>CGG--GCAG}GCGCCGAGGGUAGGGCCCGUGACUGGGGCGAAGUCGUAACAAG-GU-AGCUGUACC<GGAA>GGUGCGGCU-GGAUCACUUUCU';

[i1,i2] = pGetAlignedIndices(ES,TS);

a = a+1;
Al(a).ModelStructure = i1;
Al(a).InferStructure = i2;
Al(a).Name           = 'JAR3D 2002 IM';

% --------------------------------------- Needleman-Wunsch alignment

for w = 1:2,
  if any(a+1 == AnalyzeList),

%    [matches,align1,align2,s1,s2] = zNeedlemanWunsch(cat(2,File(1).NT.Base),cat(2,File(2).NT.Base),2*w);
    g = -6.56 + 0.02*w;
    [matches,align1,align2,s1,s2] = dNeedlemanWunsch(cat(2,File(1).NT.Base),cat(2,File(2).NT.Base),0.8,g);      % Ryan's alignment has 80% identical

    a = a+1;
    Al(a).ModelStructure = align1;
    Al(a).InferStructure = align2;
    Al(a).Name           = ['NW del ' num2str(g)];
  end
end

%------------------------------------------------------------------------
% --------------------------------------- Calculations for each alignment

for a = AnalyzeList,
  Al(a).Matrix = sparse(Al(a).ModelStructure,Al(a).InferStructure,ones(1,length(Al(a).ModelStructure)));

  Al(a).Matrix(length(File(1).NT),1) = 0;    % make the matrix bigger
  Al(a).Matrix(1,length(File(2).NT)) = 0;

  if Verbose > 1,
    Al(a).Tally = zAlignmentDiagram(File,Al(a).ModelStructure,Al(a).InferStructure,1);
  else
    Al(a).Tally = zAlignmentDiagram(File,Al(a).ModelStructure,Al(a).InferStructure,0);
  end
end

% --------------------------------------- Superimpose local neighborhoods

for a = AnalyzeList,
  Al(a).Discrep = zHistogramDiscrepanciesInAlignment(File,Al(a).ModelStructure,Al(a).InferStructure);
end

figure(10)
clf

m = 3;
s = ceil(sqrt(length(Al)));
for a = 1:length(Al),
  subplot(s,s,a)
  if length(Al(a).Discrep) > 0,
    n = hist(min(Al(a).Discrep,m),-0.025+(0:0.05:m));
    hist(min(Al(a).Discrep,m),-0.025+(0:0.05:m))
    axis([0 m 0 max(n)*1.1])
  end
  title(Al(a).Name);
end

saveas(gcf,'Histogram Discrepancies in 16S Alignments.pdf','pdf')

% -------------------------------- Calculate IDI of aligned base combinations 
%                                  with basepairs in 3D structure

for a = AnalyzeList,
  Al(a).IDI     = zAlignmentIsostericity(File,Al(a).ModelStructure,Al(a).InferStructure);
end

figure(11)
clf

m = 10;
s = ceil(sqrt(length(Al)));
for a = 1:length(Al),
  subplot(s,s,a)
  if length(Al(a).IDI) > 0,
    n = hist(min(Al(a).IDI,m),-0.025+(0:0.05:m));
    hist(min(Al(a).IDI,m),-0.025+(0:0.05:m))
    axis([-1 m 0 max(n)*1.1])
  end
  title(Al(a).Name);
end

saveas(gcf,'Histogram of IDI values in 16S Alignments.pdf','pdf')




% --------------------------------------- Compare to Alignment 1

for a = AnalyzeList,
  Agree  = sum(sum(Al(a).Matrix .* Al(1).Matrix == 1));  % where they agree
  Missed = sum(sum(Al(1).Matrix > Al(a).Matrix));
  Extra  = sum(sum(Al(a).Matrix > Al(1).Matrix));
  Identical = length(find(cat(1,File(1).NT(Al(a).ModelStructure).Code)==cat(1,File(2).NT(Al(a).InferStructure).Code)));


  % ----------------- Find identical pairs that also correspond to alignment 1

  [i,j,k] = find(Al(a).Matrix .* Al(1).Matrix); % part of alignment that agrees

  Al1 = i';
  Al2 = j';

  E1 = fix(File(1).Edge);                         % interactions in File 1
  E1 = E1 - 2*E1.*((E1 == -1) + (E1 == -2) + (E1 == -7) + (E1 == -8) + (E1 == -11) + (E1 == -12));                            % use abs values for these pairs

  E2 = fix(File(2).Edge);
  E2 = E2 - 2*E2.*((E2 == -1) + (E2 == -2) + (E2 == -7) + (E2 == -8) + (E2 == -11) + (E2 == -12));

  FF = File(2);
  FF.Edge = FF.Edge(Al2,Al2) .* (E1(Al1,Al1) == E2(Al2,Al2));

%  Tally = zSummarizeInteractions(FF,0);

  BP1 = fix(NewFile(1).BasePhosphate);
  BP2 = fix(NewFile(2).BasePhosphate);





  Tally = zAlignmentDiagram(File,i',j',0);

  T{ 1,a+1} = Al(a).Name;
  T{ 2,a+1} = length(Al(a).ModelStructure);
  for v = 1:6,
    T{v+2,a+1} = Tally(v);
  end
  T{ 9,a+1} = Agree;
  T{10,a+1} = Missed;
  T{11,a+1} = Extra;
  T{12,a+1} = mean(Al(a).Discrep);
  T{13,a+1} = median(Al(a).Discrep);
  T{14,a+1} = mean(Al(a).IDI);
  T{15,a+1} = median(Al(a).IDI);
  T{16,a+1} = Identical;
  for v = 1:6,
    T{v+16,a+1} = Al(a).Tally(v);
  end
end

T{ 1,1} = [File(1).Filename ' as the model, ' File(2).Filename ' as the unknown structure'];
T{ 2,1} = 'Number aligned';
T{ 3,1} = ['Nested cWW correctly inferred and placed in' File(2).Filename];
T{ 4,1} = ['Nested non-cWW correctly inferred and placed in ' File(2).Filename];
T{ 5,1} = ['Non-nested cWW correctly inferred and placed in ' File(2).Filename];
T{ 6,1} = ['Non-nested non-cWW correctly inferred and placed in ' File(2).Filename];
T{ 7,1} = ['Stacking correctly inferred and placed in ' File(2).Filename];
T{ 8,1} = ['Base-phosphate correctly inferred and placed in ' File(2).Filename];
T{ 9,1} = ['Number of correspondences agreeing with ' Al(1).Name];
T{10,1} = ['Number of correspondences missing, compared to ' Al(1).Name];
T{11,1} = ['Number of correspondences extra, compared to ' Al(1).Name];
T{12,1} = 'Mean geometric discrepancy at 8 Angstroms';
T{13,1} = 'Median geometric discrepancy at 8 Angstroms';
T{14,1} = 'Mean IDI between aligned base combinations and real pairs';
T{15,1} = 'Median IDI between aligned base combinations and real pairs';
T{16,1} = 'Number of exact base matches in alignment';
T{17,1} = 'Nested cWW correctly inferred, maybe not placed right ';
T{18,1} = 'Nested non-cWW correctly inferred, maybe not placed right ';
T{19,1} = 'Non-nested cWW correctly inferred, maybe not placed right ';
T{20,1} = 'Non-nested non-cWW correctly inferred, maybe not placed right ';
T{21,1} = 'Stacking correctly inferred, maybe not placed right ';
T{22,1} = 'Base-phosphate correctly inferred, maybe not placed right ';

xlswrite('16S_alignment_comparison.xls',T);

T

% ---------------------------------------- Visually compare to Alignment 1

if Verbose > 1,

  for a = AnalyzeList,
    if a ~= 1,
      clf
      zCompareAlignment(File,Al(1).ModelStructure,Al(1).InferStructure,Al(a).ModelStructure,Al(a).InferStructure,Al(1).Name,Al(a).Name);
      Titl = ['Agreement between ' Al(a).Name ' and ' Al(1).Name];
%  title(Titl);
      saveas(gcf,[strrep(Titl,' ','_') '.pdf'],'pdf');
    end
end

end
