
fprintf('Nucleotide mask, location weight, and angle weight are specified \n');
fprintf('in the boxes on the diagonal\n');
fprintf('\n');
fprintf('For the mask, type A to allow only A''s, similarly with C, G, U.\n');
fprintf('Type AC to allow only A or C, or AGU to allow only A, G, or U.\n');
fprintf('Type ~G to exclude G (or type ACU).\n');
fprintf('You may use one of these standard abbreviations:\n');
fprintf('  M = AC;  R = AG;  W = AU;  S = CG;  Y = CU;  K = GU\n');
fprintf('  V = ACG; H = ACU; D = AGU; B = CGU; N = ACGU\n');
fprintf('Using no mask is the same as specifying ACGU or N.\n');
fprintf('Self-contradictory specifications (such as A ~A) may give\n');
fprintf('unpredictable results or empty searches.\n');
fprintf('\n');
fprintf('Specify the location weight for the given nucleotide by typing\n');
fprintf('something of the form LW2.5 in the box.\n');
fprintf('Location weights are normalized automatically, so making them\n');
fprintf('all equal to 5.0 has no effect on the search.\n');
fprintf('The default value, if nothing is specified, is 1.0.\n');
fprintf('\n');
fprintf('Specify the angle weight for the given nucleotide by typing\n');
fprintf('something of the form AW2.0 in the box.\n');
fprintf('Angle weights are not automatically normalized; the default is 1.0.\n');
fprintf('Making angle weights larger than 1.0 increases the orientation error.\n');
fprintf('Thus, candidates with low discrepancy will have bases more closely\n');
fprintf('aligned than when using the default value of 1.0 for angle weight.\n');
fprintf('\n');
fprintf('Separate the mask, location weight, and angle weight by spaces.\n');
fprintf('\n');
fprintf('\n');
fprintf('\n');
fprintf('\n');
fprintf('\n');
